agent_id = "agent_9201kvzmk05dfc0atefrhdz75exa"
agent_name = "Voice Agent Service Center - Intoxalock - Development"
tags = ["intoxalock", "device-removal", "dev", "mindr"]
phone_number_id = "phnum_5501kvxnv1y0ea0r36rk6bpkpcva"
webhook_base_url = "https://webhook.free.beeceptor.com"
save_tool_id = "tool_4901kx666gzzf0p8z552c0a3gjtn"
concurrency_limit = 1
